Dockerize swarm and create a bash script
Firstset/validator-swarm pull request #30
Opened 2024-12-27 11:51 UTC by vlddlv

2025-01-10 09:20 UTC, bernatfp commented on Dockerfile
> +COPY /.ssh /root/.ssh
shouldn't this be `~/.ssh`?

2025-01-10 09:21 UTC, bernatfp commented on Dockerfile
> +# Print architecture information for debugging
if this is for debugging, shouldn't we remove it now?

2025-01-10 09:23 UTC, bernatfp commented on Dockerfile
> +# Final verification of deposit CLI
this seems like a debugging step? do we need it?

2025-01-10 09:25 UTC, bernatfp commented on config.toml.holesky.example
> -[remote_signer]
we shouldn't remove this section from the example file - the example file needs to have all parameters including optional ones

2025-01-10 09:26 UTC, bernatfp requested changes
Looks good, except for a couple of things. Left a few comments.

I will also test it out a bit separately.

2025-01-10 10:12 UTC, vlddlv commented on Dockerfile
> +# Print architecture information for debugging
it copies to a local directory first where it mounts from, that's the only way I found feasible.

2025-01-10 10:13 UTC, vlddlv commented on Dockerfile
> +COPY /.ssh /root/.ssh
it copies to a local directory first where it mounts from, that's the only way I found feasible.

2025-01-13 10:44 UTC, bernatfp commented on config.toml.holesky.example
> -[remote_signer]
@vlddlv

2025-01-13 17:26 UTC, bernatfp approved these changes

2025-01-13 17:27 UTC, bernatfp approved these changes

2025-01-13 17:30 UTC, merged